//
// DO NOT MODIFY! THIS IS AUTOGENERATED FILE!
//
namespace Xilium.CefGlue.Interop
{
    using System;
    using System.Diagnostics.CodeAnalysis;
    using System.Runtime.InteropServices;
    using System.Security;
    
    [StructLayout(LayoutKind.Sequential, Pack = libcef.ALIGN)]
    [SuppressMessage("Microsoft.Design", "CA1049:TypesThatOwnNativeResourcesShouldBeDisposable")]
    internal unsafe struct cef_component_updater_t
    {
        internal cef_base_ref_counted_t _base;
        internal IntPtr _get_component_count;
        internal IntPtr _get_components;
        internal IntPtr _get_component_by_id;
        internal IntPtr _update;
        
        // GetComponentUpdater
        [DllImport(libcef.DllName, EntryPoint = "cef_component_updater_get", CallingConvention = libcef.CEF_CALL)]
        public static extern cef_component_updater_t* get();
        
        [UnmanagedFunctionPointer(libcef.CEF_CALLBACK)]
        #if !DEBUG
        [SuppressUnmanagedCodeSecurity]
        #endif
        private delegate void add_ref_delegate(cef_component_updater_t* self);
        
        [UnmanagedFunctionPointer(libcef.CEF_CALLBACK)]
        #if !DEBUG
        [SuppressUnmanagedCodeSecurity]
        #endif
        private delegate int release_delegate(cef_component_updater_t* self);
        
        [UnmanagedFunctionPointer(libcef.CEF_CALLBACK)]
        #if !DEBUG
        [SuppressUnmanagedCodeSecurity]
        #endif
        private delegate int has_one_ref_delegate(cef_component_updater_t* self);
        
        [UnmanagedFunctionPointer(libcef.CEF_CALLBACK)]
        #if !DEBUG
        [SuppressUnmanagedCodeSecurity]
        #endif
        private delegate int has_at_least_one_ref_delegate(cef_component_updater_t* self);
        
        [UnmanagedFunctionPointer(libcef.CEF_CALLBACK)]
        #if !DEBUG
        [SuppressUnmanagedCodeSecurity]
        #endif
        private delegate UIntPtr get_component_count_delegate(cef_component_updater_t* self);
        
        [UnmanagedFunctionPointer(libcef.CEF_CALLBACK)]
        #if !DEBUG
        [SuppressUnmanagedCodeSecurity]
        #endif
        private delegate void get_components_delegate(cef_component_updater_t* self, UIntPtr* componentsCount, cef_component_t** components);
        
        [UnmanagedFunctionPointer(libcef.CEF_CALLBACK)]
        #if !DEBUG
        [SuppressUnmanagedCodeSecurity]
        #endif
        private delegate cef_component_t* get_component_by_id_delegate(cef_component_updater_t* self, cef_string_t* component_id);
        
        [UnmanagedFunctionPointer(libcef.CEF_CALLBACK)]
        #if !DEBUG
        [SuppressUnmanagedCodeSecurity]
        #endif
        private delegate void update_delegate(cef_component_updater_t* self, cef_string_t* component_id, CefComponentUpdatePriority priority, cef_component_update_callback_t* callback);
        
        // AddRef
        private static IntPtr _p0;
        private static add_ref_delegate _d0;
        
        public static void add_ref(cef_component_updater_t* self)
        {
            add_ref_delegate d;
            var p = self->_base._add_ref;
            if (p == _p0) { d = _d0; }
            else
            {
                d = (add_ref_delegate)Marshal.GetDelegateForFunctionPointer(p, typeof(add_ref_delegate));
                if (_p0 == IntPtr.Zero) { _d0 = d; _p0 = p; }
            }
            d(self);
        }
        
        // Release
        private static IntPtr _p1;
        private static release_delegate _d1;
        
        public static int release(cef_component_updater_t* self)
        {
            release_delegate d;
            var p = self->_base._release;
            if (p == _p1) { d = _d1; }
            else
            {
                d = (release_delegate)Marshal.GetDelegateForFunctionPointer(p, typeof(release_delegate));
                if (_p1 == IntPtr.Zero) { _d1 = d; _p1 = p; }
            }
            return d(self);
        }
        
        // HasOneRef
        private static IntPtr _p2;
        private static has_one_ref_delegate _d2;
        
        public static int has_one_ref(cef_component_updater_t* self)
        {
            has_one_ref_delegate d;
            var p = self->_base._has_one_ref;
            if (p == _p2) { d = _d2; }
            else
            {
                d = (has_one_ref_delegate)Marshal.GetDelegateForFunctionPointer(p, typeof(has_one_ref_delegate));
                if (_p2 == IntPtr.Zero) { _d2 = d; _p2 = p; }
            }
            return d(self);
        }
        
        // HasAtLeastOneRef
        private static IntPtr _p3;
        private static has_at_least_one_ref_delegate _d3;
        
        public static int has_at_least_one_ref(cef_component_updater_t* self)
        {
            has_at_least_one_ref_delegate d;
            var p = self->_base._has_at_least_one_ref;
            if (p == _p3) { d = _d3; }
            else
            {
                d = (has_at_least_one_ref_delegate)Marshal.GetDelegateForFunctionPointer(p, typeof(has_at_least_one_ref_delegate));
                if (_p3 == IntPtr.Zero) { _d3 = d; _p3 = p; }
            }
            return d(self);
        }
        
        // GetComponentCount
        private static IntPtr _p4;
        private static get_component_count_delegate _d4;
        
        public static UIntPtr get_component_count(cef_component_updater_t* self)
        {
            get_component_count_delegate d;
            var p = self->_get_component_count;
            if (p == _p4) { d = _d4; }
            else
            {
                d = (get_component_count_delegate)Marshal.GetDelegateForFunctionPointer(p, typeof(get_component_count_delegate));
                if (_p4 == IntPtr.Zero) { _d4 = d; _p4 = p; }
            }
            return d(self);
        }
        
        // GetComponents
        private static IntPtr _p5;
        private static get_components_delegate _d5;
        
        public static void get_components(cef_component_updater_t* self, UIntPtr* componentsCount, cef_component_t** components)
        {
            get_components_delegate d;
            var p = self->_get_components;
            if (p == _p5) { d = _d5; }
            else
            {
                d = (get_components_delegate)Marshal.GetDelegateForFunctionPointer(p, typeof(get_components_delegate));
                if (_p5 == IntPtr.Zero) { _d5 = d; _p5 = p; }
            }
            d(self, componentsCount, components);
        }
        
        // GetComponentByID
        private static IntPtr _p6;
        private static get_component_by_id_delegate _d6;
        
        public static cef_component_t* get_component_by_id(cef_component_updater_t* self, cef_string_t* component_id)
        {
            get_component_by_id_delegate d;
            var p = self->_get_component_by_id;
            if (p == _p6) { d = _d6; }
            else
            {
                d = (get_component_by_id_delegate)Marshal.GetDelegateForFunctionPointer(p, typeof(get_component_by_id_delegate));
                if (_p6 == IntPtr.Zero) { _d6 = d; _p6 = p; }
            }
            return d(self, component_id);
        }
        
        // Update
        private static IntPtr _p7;
        private static update_delegate _d7;
        
        public static void update(cef_component_updater_t* self, cef_string_t* component_id, CefComponentUpdatePriority priority, cef_component_update_callback_t* callback)
        {
            update_delegate d;
            var p = self->_update;
            if (p == _p7) { d = _d7; }
            else
            {
                d = (update_delegate)Marshal.GetDelegateForFunctionPointer(p, typeof(update_delegate));
                if (_p7 == IntPtr.Zero) { _d7 = d; _p7 = p; }
            }
            d(self, component_id, priority, callback);
        }
        
    }
}
