//
// DO NOT MODIFY! THIS IS AUTOGENERATED FILE!
//
namespace Xilium.CefGlue.Interop
{
    using System;
    using System.Runtime.InteropServices;
    using System.Diagnostics.CodeAnalysis;
    
    internal static unsafe partial class libcef
    {
        public const string CEF_VERSION = "149.0.4+g2f1bfd8+chromium-149.0.7827.156";
        public const int CEF_VERSION_MAJOR = 149;
        public const int CEF_COMMIT_NUMBER = 3528;
        public const string CEF_COMMIT_HASH = "2f1bfd842a0b6a9e770b708654986b6e5f17d772";
        
        public const int CHROME_VERSION_MAJOR = 149;
        public const int CHROME_VERSION_MINOR = 0;
        public const int CHROME_VERSION_BUILD = 7827;
        public const int CHROME_VERSION_PATCH = 156;
        
        public const int CEF_API_VERSION = 14900;
        public const string CEF_API_HASH_PLATFORM_WIN = "de5114c34e4c0c3d725313c38f4ed5b18cbfdeb4";
        public const string CEF_API_HASH_PLATFORM_MACOS = "22fd845554eb5e3f5516965213efca951a3f8256";
        public const string CEF_API_HASH_PLATFORM_LINUX = "778f64e58ff024840e29fb49bb7b9c3819f12191";
    }
}
