<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>$(DotnetVersion)</TargetFramework>
    <PackageId>CefGlue.BrowserProcess.runtime.win.jit</PackageId>
    <Version>$(Version)</Version>
    <Authors>$(Authors)</Authors>
    <Description>Meta package - includes Windows JIT (self-contained) BrowserProcess binaries for win-x64 and win-arm64. Install alongside CefGlue.Common.</Description>
    <IncludeBuildOutput>false</IncludeBuildOutput>
    <NoWarn>$(NoWarn);NU5100;NU5118</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\CefGlue.BrowserProcess.runtime.win-x64.jit\CefGlue.BrowserProcess.runtime.win-x64.jit.csproj" />
    <ProjectReference Include="..\CefGlue.BrowserProcess.runtime.win-arm64.jit\CefGlue.BrowserProcess.runtime.win-arm64.jit.csproj" />
  </ItemGroup>
</Project>